
// <auto-generated>
// この .cs ファイルはT4によって自動的に生成されています。直接編集はせず、代わりに .tt ファイルを編集してください。
// </auto-generated>

namespace CyclicRedundancyChecks
{
    /// <summary>
    /// 既定の CRC 仕様を表す <see cref="CRCSpec"/> の実装を提供します。
    /// </summary>
    /// <remarks>このクラスの <see cref="CRCSpec"/> は <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> の内容に準拠しています。</remarks>
    public static class Catalog
    {
        /// <summary>
        /// <para>CRC アルゴリズム "CRC-3/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03</b>, <i>InitialValue </i>: <b>0x00</b>, <i>FinalXorValue</i>: <b>0x07</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC3_GSM
            = new CRCSpec(3, (ulong)0x03, (ulong)0x00, (ulong)0x07, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-3/ROHC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03</b>, <i>InitialValue </i>: <b>0x07</b>, <i>FinalXorValue</i>: <b>0x00</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC3_ROHC
            = new CRCSpec(3, (ulong)0x03, (ulong)0x07, (ulong)0x00, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-4/G-704" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03</b>, <i>InitialValue </i>: <b>0x00</b>, <i>FinalXorValue</i>: <b>0x00</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC4_G_704
            = new CRCSpec(4, (ulong)0x03, (ulong)0x00, (ulong)0x00, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-4/INTERLAKEN" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03</b>, <i>InitialValue </i>: <b>0x0f</b>, <i>FinalXorValue</i>: <b>0x0f</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC4_INTERLAKEN
            = new CRCSpec(4, (ulong)0x03, (ulong)0x0f, (ulong)0x0f, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-5/EPC-C1G2" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x009</b>, <i>InitialValue </i>: <b>0x009</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC5_EPC_C1G2
            = new CRCSpec(5, (ulong)0x009, (ulong)0x009, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-5/G-704" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x015</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC5_G_704
            = new CRCSpec(5, (ulong)0x015, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-5/USB" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x005</b>, <i>InitialValue </i>: <b>0x01f</b>, <i>FinalXorValue</i>: <b>0x01f</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC5_USB
            = new CRCSpec(5, (ulong)0x005, (ulong)0x01f, (ulong)0x01f, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-6/CDMA2000-A" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x027</b>, <i>InitialValue </i>: <b>0x03f</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC6_CDMA2000_A
            = new CRCSpec(6, (ulong)0x027, (ulong)0x03f, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-6/CDMA2000-B" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x007</b>, <i>InitialValue </i>: <b>0x03f</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC6_CDMA2000_B
            = new CRCSpec(6, (ulong)0x007, (ulong)0x03f, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-6/DARC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x019</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC6_DARC
            = new CRCSpec(6, (ulong)0x019, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-6/G-704" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x003</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC6_G_704
            = new CRCSpec(6, (ulong)0x003, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-6/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x02f</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x03f</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC6_GSM
            = new CRCSpec(6, (ulong)0x02f, (ulong)0x000, (ulong)0x03f, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-7/MMC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x009</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC7_MMC
            = new CRCSpec(7, (ulong)0x009, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-7/ROHC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x04f</b>, <i>InitialValue </i>: <b>0x07f</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC7_ROHC
            = new CRCSpec(7, (ulong)0x04f, (ulong)0x07f, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-7/UMTS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x045</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC7_UMTS
            = new CRCSpec(7, (ulong)0x045, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/AUTOSAR" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x02f</b>, <i>InitialValue </i>: <b>0x0ff</b>, <i>FinalXorValue</i>: <b>0x0ff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_AUTOSAR
            = new CRCSpec(8, (ulong)0x02f, (ulong)0x0ff, (ulong)0x0ff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/BLUETOOTH" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0a7</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_BLUETOOTH
            = new CRCSpec(8, (ulong)0x0a7, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/CDMA2000" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x09b</b>, <i>InitialValue </i>: <b>0x0ff</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_CDMA2000
            = new CRCSpec(8, (ulong)0x09b, (ulong)0x0ff, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/DARC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x039</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_DARC
            = new CRCSpec(8, (ulong)0x039, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/DVB-S2" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0d5</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_DVB_S2
            = new CRCSpec(8, (ulong)0x0d5, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/GSM-A" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01d</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_GSM_A
            = new CRCSpec(8, (ulong)0x01d, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/GSM-B" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x049</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x0ff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_GSM_B
            = new CRCSpec(8, (ulong)0x049, (ulong)0x000, (ulong)0x0ff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/I-432-1" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x007</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x055</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_I_432_1
            = new CRCSpec(8, (ulong)0x007, (ulong)0x000, (ulong)0x055, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/I-CODE" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01d</b>, <i>InitialValue </i>: <b>0x0fd</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_I_CODE
            = new CRCSpec(8, (ulong)0x01d, (ulong)0x0fd, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/LTE" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x09b</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_LTE
            = new CRCSpec(8, (ulong)0x09b, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/MAXIM-DOW" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x031</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_MAXIM_DOW
            = new CRCSpec(8, (ulong)0x031, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/MIFARE-MAD" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01d</b>, <i>InitialValue </i>: <b>0x0c7</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_MIFARE_MAD
            = new CRCSpec(8, (ulong)0x01d, (ulong)0x0c7, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/NRSC-5" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x031</b>, <i>InitialValue </i>: <b>0x0ff</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_NRSC_5
            = new CRCSpec(8, (ulong)0x031, (ulong)0x0ff, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/OPENSAFETY" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x02f</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_OPENSAFETY
            = new CRCSpec(8, (ulong)0x02f, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/ROHC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x007</b>, <i>InitialValue </i>: <b>0x0ff</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_ROHC
            = new CRCSpec(8, (ulong)0x007, (ulong)0x0ff, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/SAE-J1850" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01d</b>, <i>InitialValue </i>: <b>0x0ff</b>, <i>FinalXorValue</i>: <b>0x0ff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_SAE_J1850
            = new CRCSpec(8, (ulong)0x01d, (ulong)0x0ff, (ulong)0x0ff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/SMBUS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x007</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_SMBUS
            = new CRCSpec(8, (ulong)0x007, (ulong)0x000, (ulong)0x000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/TECH-3250" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01d</b>, <i>InitialValue </i>: <b>0x0ff</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_TECH_3250
            = new CRCSpec(8, (ulong)0x01d, (ulong)0x0ff, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-8/WCDMA" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x09b</b>, <i>InitialValue </i>: <b>0x000</b>, <i>FinalXorValue</i>: <b>0x000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC8_WCDMA
            = new CRCSpec(8, (ulong)0x09b, (ulong)0x000, (ulong)0x000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-10/ATM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0233</b>, <i>InitialValue </i>: <b>0x0000</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC10_ATM
            = new CRCSpec(10, (ulong)0x0233, (ulong)0x0000, (ulong)0x0000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-10/CDMA2000" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03d9</b>, <i>InitialValue </i>: <b>0x03ff</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC10_CDMA2000
            = new CRCSpec(10, (ulong)0x03d9, (ulong)0x03ff, (ulong)0x0000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-10/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0175</b>, <i>InitialValue </i>: <b>0x0000</b>, <i>FinalXorValue</i>: <b>0x03ff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC10_GSM
            = new CRCSpec(10, (ulong)0x0175, (ulong)0x0000, (ulong)0x03ff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-11/FLEXRAY" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0385</b>, <i>InitialValue </i>: <b>0x001a</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC11_FLEXRAY
            = new CRCSpec(11, (ulong)0x0385, (ulong)0x001a, (ulong)0x0000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-11/UMTS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0307</b>, <i>InitialValue </i>: <b>0x0000</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC11_UMTS
            = new CRCSpec(11, (ulong)0x0307, (ulong)0x0000, (ulong)0x0000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-12/CDMA2000" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0f13</b>, <i>InitialValue </i>: <b>0x0fff</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC12_CDMA2000
            = new CRCSpec(12, (ulong)0x0f13, (ulong)0x0fff, (ulong)0x0000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-12/DECT" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x080f</b>, <i>InitialValue </i>: <b>0x0000</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC12_DECT
            = new CRCSpec(12, (ulong)0x080f, (ulong)0x0000, (ulong)0x0000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-12/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0d31</b>, <i>InitialValue </i>: <b>0x0000</b>, <i>FinalXorValue</i>: <b>0x0fff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC12_GSM
            = new CRCSpec(12, (ulong)0x0d31, (ulong)0x0000, (ulong)0x0fff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-12/UMTS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x080f</b>, <i>InitialValue </i>: <b>0x0000</b>, <i>FinalXorValue</i>: <b>0x0000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC12_UMTS
            = new CRCSpec(12, (ulong)0x080f, (ulong)0x0000, (ulong)0x0000, false, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-13/BBC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01cf5</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC13_BBC
            = new CRCSpec(13, (ulong)0x01cf5, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-14/DARC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x00805</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC14_DARC
            = new CRCSpec(14, (ulong)0x00805, (ulong)0x00000, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-14/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0202d</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x03fff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC14_GSM
            = new CRCSpec(14, (ulong)0x0202d, (ulong)0x00000, (ulong)0x03fff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-15/CAN" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x04599</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC15_CAN
            = new CRCSpec(15, (ulong)0x04599, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-15/MPT1327" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x06815</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00001</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC15_MPT1327
            = new CRCSpec(15, (ulong)0x06815, (ulong)0x00000, (ulong)0x00001, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/ARC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_ARC
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x00000, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/CDMA2000" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0c867</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_CDMA2000
            = new CRCSpec(16, (ulong)0x0c867, (ulong)0x0ffff, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/CMS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_CMS
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x0ffff, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/DDS-110" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x0800d</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_DDS_110
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x0800d, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/DECT-R" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x00589</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00001</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_DECT_R
            = new CRCSpec(16, (ulong)0x00589, (ulong)0x00000, (ulong)0x00001, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/DECT-X" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x00589</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_DECT_X
            = new CRCSpec(16, (ulong)0x00589, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/DNP" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03d65</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_DNP
            = new CRCSpec(16, (ulong)0x03d65, (ulong)0x00000, (ulong)0x0ffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/EN-13757" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x03d65</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_EN_13757
            = new CRCSpec(16, (ulong)0x03d65, (ulong)0x00000, (ulong)0x0ffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/GENIBUS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_GENIBUS
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x0ffff, (ulong)0x0ffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_GSM
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x00000, (ulong)0x0ffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/IBM-3740" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_IBM_3740
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x0ffff, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/IBM-SDLC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_IBM_SDLC
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x0ffff, (ulong)0x0ffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/ISO-IEC-14443-3-A" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x0c6c6</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_ISO_IEC_14443_3_A
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x0c6c6, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/KERMIT" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_KERMIT
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x00000, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/LJ1200" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x06f63</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_LJ1200
            = new CRCSpec(16, (ulong)0x06f63, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/MAXIM-DOW" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_MAXIM_DOW
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x00000, (ulong)0x0ffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/MCRF4XX" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_MCRF4XX
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x0ffff, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/MODBUS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_MODBUS
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x0ffff, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/NRSC-5" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0080b</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_NRSC_5
            = new CRCSpec(16, (ulong)0x0080b, (ulong)0x0ffff, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/OPENSAFETY-A" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x05935</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_OPENSAFETY_A
            = new CRCSpec(16, (ulong)0x05935, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/OPENSAFETY-B" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0755b</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_OPENSAFETY_B
            = new CRCSpec(16, (ulong)0x0755b, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/PROFIBUS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01dcf</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_PROFIBUS
            = new CRCSpec(16, (ulong)0x01dcf, (ulong)0x0ffff, (ulong)0x0ffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/RIELLO" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x0b2aa</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_RIELLO
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x0b2aa, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/SPI-FUJITSU" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x01d0f</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_SPI_FUJITSU
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x01d0f, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/T10-DIF" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08bb7</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_T10_DIF
            = new CRCSpec(16, (ulong)0x08bb7, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/TELEDISK" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0a097</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_TELEDISK
            = new CRCSpec(16, (ulong)0x0a097, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/TMS37157" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x089ec</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_TMS37157
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x089ec, (ulong)0x00000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/UMTS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_UMTS
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/USB" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08005</b>, <i>InitialValue </i>: <b>0x0ffff</b>, <i>FinalXorValue</i>: <b>0x0ffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_USB
            = new CRCSpec(16, (ulong)0x08005, (ulong)0x0ffff, (ulong)0x0ffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-16/XMODEM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01021</b>, <i>InitialValue </i>: <b>0x00000</b>, <i>FinalXorValue</i>: <b>0x00000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC16_XMODEM
            = new CRCSpec(16, (ulong)0x01021, (ulong)0x00000, (ulong)0x00000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-17/CAN-FD" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01685b</b>, <i>InitialValue </i>: <b>0x000000</b>, <i>FinalXorValue</i>: <b>0x000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC17_CAN_FD
            = new CRCSpec(17, (ulong)0x01685b, (ulong)0x000000, (ulong)0x000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-21/CAN-FD" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0102899</b>, <i>InitialValue </i>: <b>0x0000000</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC21_CAN_FD
            = new CRCSpec(21, (ulong)0x0102899, (ulong)0x0000000, (ulong)0x0000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/BLE" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x000065b</b>, <i>InitialValue </i>: <b>0x0555555</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_BLE
            = new CRCSpec(24, (ulong)0x000065b, (ulong)0x0555555, (ulong)0x0000000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/FLEXRAY-A" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x05d6dcb</b>, <i>InitialValue </i>: <b>0x0fedcba</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_FLEXRAY_A
            = new CRCSpec(24, (ulong)0x05d6dcb, (ulong)0x0fedcba, (ulong)0x0000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/FLEXRAY-B" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x05d6dcb</b>, <i>InitialValue </i>: <b>0x0abcdef</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_FLEXRAY_B
            = new CRCSpec(24, (ulong)0x05d6dcb, (ulong)0x0abcdef, (ulong)0x0000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/INTERLAKEN" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0328b63</b>, <i>InitialValue </i>: <b>0x0ffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_INTERLAKEN
            = new CRCSpec(24, (ulong)0x0328b63, (ulong)0x0ffffff, (ulong)0x0ffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/LTE-A" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0864cfb</b>, <i>InitialValue </i>: <b>0x0000000</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_LTE_A
            = new CRCSpec(24, (ulong)0x0864cfb, (ulong)0x0000000, (ulong)0x0000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/LTE-B" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0800063</b>, <i>InitialValue </i>: <b>0x0000000</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_LTE_B
            = new CRCSpec(24, (ulong)0x0800063, (ulong)0x0000000, (ulong)0x0000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/OPENPGP" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0864cfb</b>, <i>InitialValue </i>: <b>0x0b704ce</b>, <i>FinalXorValue</i>: <b>0x0000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_OPENPGP
            = new CRCSpec(24, (ulong)0x0864cfb, (ulong)0x0b704ce, (ulong)0x0000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-24/OS-9" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0800063</b>, <i>InitialValue </i>: <b>0x0ffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC24_OS_9
            = new CRCSpec(24, (ulong)0x0800063, (ulong)0x0ffffff, (ulong)0x0ffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-30/CDMA" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x02030b9c7</b>, <i>InitialValue </i>: <b>0x03fffffff</b>, <i>FinalXorValue</i>: <b>0x03fffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC30_CDMA
            = new CRCSpec(30, (ulong)0x02030b9c7, (ulong)0x03fffffff, (ulong)0x03fffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-31/PHILIPS" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x004c11db7</b>, <i>InitialValue </i>: <b>0x07fffffff</b>, <i>FinalXorValue</i>: <b>0x07fffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC31_PHILIPS
            = new CRCSpec(31, (ulong)0x004c11db7, (ulong)0x07fffffff, (ulong)0x07fffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/AIXM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0814141ab</b>, <i>InitialValue </i>: <b>0x000000000</b>, <i>FinalXorValue</i>: <b>0x000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_AIXM
            = new CRCSpec(32, (ulong)0x0814141ab, (ulong)0x000000000, (ulong)0x000000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/AUTOSAR" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0f4acfb13</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_AUTOSAR
            = new CRCSpec(32, (ulong)0x0f4acfb13, (ulong)0x0ffffffff, (ulong)0x0ffffffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/BASE91-D" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0a833982b</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_BASE91_D
            = new CRCSpec(32, (ulong)0x0a833982b, (ulong)0x0ffffffff, (ulong)0x0ffffffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/BZIP2" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x004c11db7</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_BZIP2
            = new CRCSpec(32, (ulong)0x004c11db7, (ulong)0x0ffffffff, (ulong)0x0ffffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/CD-ROM-EDC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x08001801b</b>, <i>InitialValue </i>: <b>0x000000000</b>, <i>FinalXorValue</i>: <b>0x000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_CD_ROM_EDC
            = new CRCSpec(32, (ulong)0x08001801b, (ulong)0x000000000, (ulong)0x000000000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/CKSUM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x004c11db7</b>, <i>InitialValue </i>: <b>0x000000000</b>, <i>FinalXorValue</i>: <b>0x0ffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_CKSUM
            = new CRCSpec(32, (ulong)0x004c11db7, (ulong)0x000000000, (ulong)0x0ffffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/ISCSI" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x01edc6f41</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_ISCSI
            = new CRCSpec(32, (ulong)0x01edc6f41, (ulong)0x0ffffffff, (ulong)0x0ffffffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/ISO-HDLC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x004c11db7</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_ISO_HDLC
            = new CRCSpec(32, (ulong)0x004c11db7, (ulong)0x0ffffffff, (ulong)0x0ffffffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/JAMCRC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x004c11db7</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_JAMCRC
            = new CRCSpec(32, (ulong)0x004c11db7, (ulong)0x0ffffffff, (ulong)0x000000000, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/MPEG-2" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x004c11db7</b>, <i>InitialValue </i>: <b>0x0ffffffff</b>, <i>FinalXorValue</i>: <b>0x000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_MPEG_2
            = new CRCSpec(32, (ulong)0x004c11db7, (ulong)0x0ffffffff, (ulong)0x000000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-32/XFER" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0000000af</b>, <i>InitialValue </i>: <b>0x000000000</b>, <i>FinalXorValue</i>: <b>0x000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC32_XFER
            = new CRCSpec(32, (ulong)0x0000000af, (ulong)0x000000000, (ulong)0x000000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-40/GSM" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x00004820009</b>, <i>InitialValue </i>: <b>0x00000000000</b>, <i>FinalXorValue</i>: <b>0x0ffffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC40_GSM
            = new CRCSpec(40, (ulong)0x00004820009, (ulong)0x00000000000, (ulong)0x0ffffffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-64/ECMA-182" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x042f0e1eba9ea3693</b>, <i>InitialValue </i>: <b>0x00000000000000000</b>, <i>FinalXorValue</i>: <b>0x00000000000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC64_ECMA_182
            = new CRCSpec(64, (ulong)0x042f0e1eba9ea3693, (ulong)0x00000000000000000, (ulong)0x00000000000000000, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-64/GO-ISO" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x0000000000000001b</b>, <i>InitialValue </i>: <b>0x0ffffffffffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffffffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC64_GO_ISO
            = new CRCSpec(64, (ulong)0x0000000000000001b, (ulong)0x0ffffffffffffffff, (ulong)0x0ffffffffffffffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-64/WE" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x042f0e1eba9ea3693</b>, <i>InitialValue </i>: <b>0x0ffffffffffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffffffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>false</b>, <i>ReflectOutput</i>: <b>false</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC64_WE
            = new CRCSpec(64, (ulong)0x042f0e1eba9ea3693, (ulong)0x0ffffffffffffffff, (ulong)0x0ffffffffffffffff, false, false);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-64/XZ" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x042f0e1eba9ea3693</b>, <i>InitialValue </i>: <b>0x0ffffffffffffffff</b>, <i>FinalXorValue</i>: <b>0x0ffffffffffffffff</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC64_XZ
            = new CRCSpec(64, (ulong)0x042f0e1eba9ea3693, (ulong)0x0ffffffffffffffff, (ulong)0x0ffffffffffffffff, true, true);

        /// <summary>
        /// <para>CRC アルゴリズム "CRC-82/DARC" の仕様を表す <see cref="CRCSpec"/> のインスタンスを取得します。( <see href="https://reveng.sourceforge.io/crc-catalogue/">Catalogue of parametrised CRC algorithms</see> )</para>
        /// </summary>
        /// <remarks>
        /// <para><i>Polynomial   </i>: <b>0x00308c0111011401440411</b>, <i>InitialValue </i>: <b>0x0000000000000000000000</b>, <i>FinalXorValue</i>: <b>0x0000000000000000000000</b></para>
        /// <para><i>ReflectInput </i>: <b>true</b>, <i>ReflectOutput</i>: <b>true</b></para>
        /// </remarks>
        public static readonly CRCSpec CRC82_DARC
            = new CRCSpec(82, global::System.Numerics.BigInteger.Parse("00308c0111011401440411", global::System.Globalization.NumberStyles.AllowHexSpecifier), global::System.Numerics.BigInteger.Parse("0000000000000000000000", global::System.Globalization.NumberStyles.AllowHexSpecifier), global::System.Numerics.BigInteger.Parse("0000000000000000000000", global::System.Globalization.NumberStyles.AllowHexSpecifier), true, true);

    }
}
