//
// CyclicRedundancyChecks
// 
// このコードはテキストテンプレートファイル (.tt) によって作成されています。
// 変更をおこなう場合は、テキストテンプレートファイル (.tt) を編集してください。
//


using System;
using System.Security.Cryptography;
using CyclicRedundancyChecks.Catalogs;

namespace CyclicRedundancyChecks
{
    partial class CRC
    {
        private static bool isRegistered = false;

        /// <summary>
        /// CRC の実装を <see cref="CryptoConfig.AddAlgorithm(Type, string[])"/> を使用して登録します。
        /// </summary>
        public static void RegisterAlgorithm()
        {
            if (isRegistered) return;

            // ハイフンなどの区切りが無い名前は、ビット幅別のクラスとして登録します。
            // これはカタログに記載されているアルゴリズムと区別させるためです。
            CryptoConfig.AddAlgorithm(typeof(CRC1), "CRC1");
            CryptoConfig.AddAlgorithm(typeof(CRC2), "CRC2");
            CryptoConfig.AddAlgorithm(typeof(CRC3), "CRC3");
            CryptoConfig.AddAlgorithm(typeof(CRC4), "CRC4");
            CryptoConfig.AddAlgorithm(typeof(CRC5), "CRC5");
            CryptoConfig.AddAlgorithm(typeof(CRC6), "CRC6");
            CryptoConfig.AddAlgorithm(typeof(CRC7), "CRC7");
            CryptoConfig.AddAlgorithm(typeof(CRC8), "CRC8");
            CryptoConfig.AddAlgorithm(typeof(CRC9), "CRC9");
            CryptoConfig.AddAlgorithm(typeof(CRC10), "CRC10");
            CryptoConfig.AddAlgorithm(typeof(CRC11), "CRC11");
            CryptoConfig.AddAlgorithm(typeof(CRC12), "CRC12");
            CryptoConfig.AddAlgorithm(typeof(CRC13), "CRC13");
            CryptoConfig.AddAlgorithm(typeof(CRC14), "CRC14");
            CryptoConfig.AddAlgorithm(typeof(CRC15), "CRC15");
            CryptoConfig.AddAlgorithm(typeof(CRC16), "CRC16");
            CryptoConfig.AddAlgorithm(typeof(CRC17), "CRC17");
            CryptoConfig.AddAlgorithm(typeof(CRC18), "CRC18");
            CryptoConfig.AddAlgorithm(typeof(CRC19), "CRC19");
            CryptoConfig.AddAlgorithm(typeof(CRC20), "CRC20");
            CryptoConfig.AddAlgorithm(typeof(CRC21), "CRC21");
            CryptoConfig.AddAlgorithm(typeof(CRC22), "CRC22");
            CryptoConfig.AddAlgorithm(typeof(CRC23), "CRC23");
            CryptoConfig.AddAlgorithm(typeof(CRC24), "CRC24");
            CryptoConfig.AddAlgorithm(typeof(CRC25), "CRC25");
            CryptoConfig.AddAlgorithm(typeof(CRC26), "CRC26");
            CryptoConfig.AddAlgorithm(typeof(CRC27), "CRC27");
            CryptoConfig.AddAlgorithm(typeof(CRC28), "CRC28");
            CryptoConfig.AddAlgorithm(typeof(CRC29), "CRC29");
            CryptoConfig.AddAlgorithm(typeof(CRC30), "CRC30");
            CryptoConfig.AddAlgorithm(typeof(CRC31), "CRC31");
            CryptoConfig.AddAlgorithm(typeof(CRC32), "CRC32");
            CryptoConfig.AddAlgorithm(typeof(CRC33), "CRC33");
            CryptoConfig.AddAlgorithm(typeof(CRC34), "CRC34");
            CryptoConfig.AddAlgorithm(typeof(CRC35), "CRC35");
            CryptoConfig.AddAlgorithm(typeof(CRC36), "CRC36");
            CryptoConfig.AddAlgorithm(typeof(CRC37), "CRC37");
            CryptoConfig.AddAlgorithm(typeof(CRC38), "CRC38");
            CryptoConfig.AddAlgorithm(typeof(CRC39), "CRC39");
            CryptoConfig.AddAlgorithm(typeof(CRC40), "CRC40");
            CryptoConfig.AddAlgorithm(typeof(CRC41), "CRC41");
            CryptoConfig.AddAlgorithm(typeof(CRC42), "CRC42");
            CryptoConfig.AddAlgorithm(typeof(CRC43), "CRC43");
            CryptoConfig.AddAlgorithm(typeof(CRC44), "CRC44");
            CryptoConfig.AddAlgorithm(typeof(CRC45), "CRC45");
            CryptoConfig.AddAlgorithm(typeof(CRC46), "CRC46");
            CryptoConfig.AddAlgorithm(typeof(CRC47), "CRC47");
            CryptoConfig.AddAlgorithm(typeof(CRC48), "CRC48");
            CryptoConfig.AddAlgorithm(typeof(CRC49), "CRC49");
            CryptoConfig.AddAlgorithm(typeof(CRC50), "CRC50");
            CryptoConfig.AddAlgorithm(typeof(CRC51), "CRC51");
            CryptoConfig.AddAlgorithm(typeof(CRC52), "CRC52");
            CryptoConfig.AddAlgorithm(typeof(CRC53), "CRC53");
            CryptoConfig.AddAlgorithm(typeof(CRC54), "CRC54");
            CryptoConfig.AddAlgorithm(typeof(CRC55), "CRC55");
            CryptoConfig.AddAlgorithm(typeof(CRC56), "CRC56");
            CryptoConfig.AddAlgorithm(typeof(CRC57), "CRC57");
            CryptoConfig.AddAlgorithm(typeof(CRC58), "CRC58");
            CryptoConfig.AddAlgorithm(typeof(CRC59), "CRC59");
            CryptoConfig.AddAlgorithm(typeof(CRC60), "CRC60");
            CryptoConfig.AddAlgorithm(typeof(CRC61), "CRC61");
            CryptoConfig.AddAlgorithm(typeof(CRC62), "CRC62");
            CryptoConfig.AddAlgorithm(typeof(CRC63), "CRC63");
            CryptoConfig.AddAlgorithm(typeof(CRC64), "CRC64");
            CryptoConfig.AddAlgorithm(typeof(CRC65), "CRC65");
            CryptoConfig.AddAlgorithm(typeof(CRC66), "CRC66");
            CryptoConfig.AddAlgorithm(typeof(CRC67), "CRC67");
            CryptoConfig.AddAlgorithm(typeof(CRC68), "CRC68");
            CryptoConfig.AddAlgorithm(typeof(CRC69), "CRC69");
            CryptoConfig.AddAlgorithm(typeof(CRC70), "CRC70");
            CryptoConfig.AddAlgorithm(typeof(CRC71), "CRC71");
            CryptoConfig.AddAlgorithm(typeof(CRC72), "CRC72");
            CryptoConfig.AddAlgorithm(typeof(CRC73), "CRC73");
            CryptoConfig.AddAlgorithm(typeof(CRC74), "CRC74");
            CryptoConfig.AddAlgorithm(typeof(CRC75), "CRC75");
            CryptoConfig.AddAlgorithm(typeof(CRC76), "CRC76");
            CryptoConfig.AddAlgorithm(typeof(CRC77), "CRC77");
            CryptoConfig.AddAlgorithm(typeof(CRC78), "CRC78");
            CryptoConfig.AddAlgorithm(typeof(CRC79), "CRC79");
            CryptoConfig.AddAlgorithm(typeof(CRC80), "CRC80");
            CryptoConfig.AddAlgorithm(typeof(CRC81), "CRC81");
            CryptoConfig.AddAlgorithm(typeof(CRC82), "CRC82");
            CryptoConfig.AddAlgorithm(typeof(CRC83), "CRC83");
            CryptoConfig.AddAlgorithm(typeof(CRC84), "CRC84");
            CryptoConfig.AddAlgorithm(typeof(CRC85), "CRC85");
            CryptoConfig.AddAlgorithm(typeof(CRC86), "CRC86");
            CryptoConfig.AddAlgorithm(typeof(CRC87), "CRC87");
            CryptoConfig.AddAlgorithm(typeof(CRC88), "CRC88");
            CryptoConfig.AddAlgorithm(typeof(CRC89), "CRC89");
            CryptoConfig.AddAlgorithm(typeof(CRC90), "CRC90");
            CryptoConfig.AddAlgorithm(typeof(CRC91), "CRC91");
            CryptoConfig.AddAlgorithm(typeof(CRC92), "CRC92");
            CryptoConfig.AddAlgorithm(typeof(CRC93), "CRC93");
            CryptoConfig.AddAlgorithm(typeof(CRC94), "CRC94");
            CryptoConfig.AddAlgorithm(typeof(CRC95), "CRC95");
            CryptoConfig.AddAlgorithm(typeof(CRC96), "CRC96");
            CryptoConfig.AddAlgorithm(typeof(CRC97), "CRC97");
            CryptoConfig.AddAlgorithm(typeof(CRC98), "CRC98");
            CryptoConfig.AddAlgorithm(typeof(CRC99), "CRC99");
            CryptoConfig.AddAlgorithm(typeof(CRC100), "CRC100");
            CryptoConfig.AddAlgorithm(typeof(CRC101), "CRC101");
            CryptoConfig.AddAlgorithm(typeof(CRC102), "CRC102");
            CryptoConfig.AddAlgorithm(typeof(CRC103), "CRC103");
            CryptoConfig.AddAlgorithm(typeof(CRC104), "CRC104");
            CryptoConfig.AddAlgorithm(typeof(CRC105), "CRC105");
            CryptoConfig.AddAlgorithm(typeof(CRC106), "CRC106");
            CryptoConfig.AddAlgorithm(typeof(CRC107), "CRC107");
            CryptoConfig.AddAlgorithm(typeof(CRC108), "CRC108");
            CryptoConfig.AddAlgorithm(typeof(CRC109), "CRC109");
            CryptoConfig.AddAlgorithm(typeof(CRC110), "CRC110");
            CryptoConfig.AddAlgorithm(typeof(CRC111), "CRC111");
            CryptoConfig.AddAlgorithm(typeof(CRC112), "CRC112");
            CryptoConfig.AddAlgorithm(typeof(CRC113), "CRC113");
            CryptoConfig.AddAlgorithm(typeof(CRC114), "CRC114");
            CryptoConfig.AddAlgorithm(typeof(CRC115), "CRC115");
            CryptoConfig.AddAlgorithm(typeof(CRC116), "CRC116");
            CryptoConfig.AddAlgorithm(typeof(CRC117), "CRC117");
            CryptoConfig.AddAlgorithm(typeof(CRC118), "CRC118");
            CryptoConfig.AddAlgorithm(typeof(CRC119), "CRC119");
            CryptoConfig.AddAlgorithm(typeof(CRC120), "CRC120");
            CryptoConfig.AddAlgorithm(typeof(CRC121), "CRC121");
            CryptoConfig.AddAlgorithm(typeof(CRC122), "CRC122");
            CryptoConfig.AddAlgorithm(typeof(CRC123), "CRC123");
            CryptoConfig.AddAlgorithm(typeof(CRC124), "CRC124");
            CryptoConfig.AddAlgorithm(typeof(CRC125), "CRC125");
            CryptoConfig.AddAlgorithm(typeof(CRC126), "CRC126");
            CryptoConfig.AddAlgorithm(typeof(CRC127), "CRC127");
            CryptoConfig.AddAlgorithm(typeof(CRC128), "CRC128");
            CryptoConfig.AddAlgorithm(typeof(CRC129), "CRC129");
            CryptoConfig.AddAlgorithm(typeof(CRC130), "CRC130");
            CryptoConfig.AddAlgorithm(typeof(CRC131), "CRC131");
            CryptoConfig.AddAlgorithm(typeof(CRC132), "CRC132");
            CryptoConfig.AddAlgorithm(typeof(CRC133), "CRC133");
            CryptoConfig.AddAlgorithm(typeof(CRC134), "CRC134");
            CryptoConfig.AddAlgorithm(typeof(CRC135), "CRC135");
            CryptoConfig.AddAlgorithm(typeof(CRC136), "CRC136");
            CryptoConfig.AddAlgorithm(typeof(CRC137), "CRC137");
            CryptoConfig.AddAlgorithm(typeof(CRC138), "CRC138");
            CryptoConfig.AddAlgorithm(typeof(CRC139), "CRC139");
            CryptoConfig.AddAlgorithm(typeof(CRC140), "CRC140");
            CryptoConfig.AddAlgorithm(typeof(CRC141), "CRC141");
            CryptoConfig.AddAlgorithm(typeof(CRC142), "CRC142");
            CryptoConfig.AddAlgorithm(typeof(CRC143), "CRC143");
            CryptoConfig.AddAlgorithm(typeof(CRC144), "CRC144");
            CryptoConfig.AddAlgorithm(typeof(CRC145), "CRC145");
            CryptoConfig.AddAlgorithm(typeof(CRC146), "CRC146");
            CryptoConfig.AddAlgorithm(typeof(CRC147), "CRC147");
            CryptoConfig.AddAlgorithm(typeof(CRC148), "CRC148");
            CryptoConfig.AddAlgorithm(typeof(CRC149), "CRC149");
            CryptoConfig.AddAlgorithm(typeof(CRC150), "CRC150");
            CryptoConfig.AddAlgorithm(typeof(CRC151), "CRC151");
            CryptoConfig.AddAlgorithm(typeof(CRC152), "CRC152");
            CryptoConfig.AddAlgorithm(typeof(CRC153), "CRC153");
            CryptoConfig.AddAlgorithm(typeof(CRC154), "CRC154");
            CryptoConfig.AddAlgorithm(typeof(CRC155), "CRC155");
            CryptoConfig.AddAlgorithm(typeof(CRC156), "CRC156");
            CryptoConfig.AddAlgorithm(typeof(CRC157), "CRC157");
            CryptoConfig.AddAlgorithm(typeof(CRC158), "CRC158");
            CryptoConfig.AddAlgorithm(typeof(CRC159), "CRC159");
            CryptoConfig.AddAlgorithm(typeof(CRC160), "CRC160");
            CryptoConfig.AddAlgorithm(typeof(CRC161), "CRC161");
            CryptoConfig.AddAlgorithm(typeof(CRC162), "CRC162");
            CryptoConfig.AddAlgorithm(typeof(CRC163), "CRC163");
            CryptoConfig.AddAlgorithm(typeof(CRC164), "CRC164");
            CryptoConfig.AddAlgorithm(typeof(CRC165), "CRC165");
            CryptoConfig.AddAlgorithm(typeof(CRC166), "CRC166");
            CryptoConfig.AddAlgorithm(typeof(CRC167), "CRC167");
            CryptoConfig.AddAlgorithm(typeof(CRC168), "CRC168");
            CryptoConfig.AddAlgorithm(typeof(CRC169), "CRC169");
            CryptoConfig.AddAlgorithm(typeof(CRC170), "CRC170");
            CryptoConfig.AddAlgorithm(typeof(CRC171), "CRC171");
            CryptoConfig.AddAlgorithm(typeof(CRC172), "CRC172");
            CryptoConfig.AddAlgorithm(typeof(CRC173), "CRC173");
            CryptoConfig.AddAlgorithm(typeof(CRC174), "CRC174");
            CryptoConfig.AddAlgorithm(typeof(CRC175), "CRC175");
            CryptoConfig.AddAlgorithm(typeof(CRC176), "CRC176");
            CryptoConfig.AddAlgorithm(typeof(CRC177), "CRC177");
            CryptoConfig.AddAlgorithm(typeof(CRC178), "CRC178");
            CryptoConfig.AddAlgorithm(typeof(CRC179), "CRC179");
            CryptoConfig.AddAlgorithm(typeof(CRC180), "CRC180");
            CryptoConfig.AddAlgorithm(typeof(CRC181), "CRC181");
            CryptoConfig.AddAlgorithm(typeof(CRC182), "CRC182");
            CryptoConfig.AddAlgorithm(typeof(CRC183), "CRC183");
            CryptoConfig.AddAlgorithm(typeof(CRC184), "CRC184");
            CryptoConfig.AddAlgorithm(typeof(CRC185), "CRC185");
            CryptoConfig.AddAlgorithm(typeof(CRC186), "CRC186");
            CryptoConfig.AddAlgorithm(typeof(CRC187), "CRC187");
            CryptoConfig.AddAlgorithm(typeof(CRC188), "CRC188");
            CryptoConfig.AddAlgorithm(typeof(CRC189), "CRC189");
            CryptoConfig.AddAlgorithm(typeof(CRC190), "CRC190");
            CryptoConfig.AddAlgorithm(typeof(CRC191), "CRC191");
            CryptoConfig.AddAlgorithm(typeof(CRC192), "CRC192");
            CryptoConfig.AddAlgorithm(typeof(CRC193), "CRC193");
            CryptoConfig.AddAlgorithm(typeof(CRC194), "CRC194");
            CryptoConfig.AddAlgorithm(typeof(CRC195), "CRC195");
            CryptoConfig.AddAlgorithm(typeof(CRC196), "CRC196");
            CryptoConfig.AddAlgorithm(typeof(CRC197), "CRC197");
            CryptoConfig.AddAlgorithm(typeof(CRC198), "CRC198");
            CryptoConfig.AddAlgorithm(typeof(CRC199), "CRC199");
            CryptoConfig.AddAlgorithm(typeof(CRC200), "CRC200");
            CryptoConfig.AddAlgorithm(typeof(CRC201), "CRC201");
            CryptoConfig.AddAlgorithm(typeof(CRC202), "CRC202");
            CryptoConfig.AddAlgorithm(typeof(CRC203), "CRC203");
            CryptoConfig.AddAlgorithm(typeof(CRC204), "CRC204");
            CryptoConfig.AddAlgorithm(typeof(CRC205), "CRC205");
            CryptoConfig.AddAlgorithm(typeof(CRC206), "CRC206");
            CryptoConfig.AddAlgorithm(typeof(CRC207), "CRC207");
            CryptoConfig.AddAlgorithm(typeof(CRC208), "CRC208");
            CryptoConfig.AddAlgorithm(typeof(CRC209), "CRC209");
            CryptoConfig.AddAlgorithm(typeof(CRC210), "CRC210");
            CryptoConfig.AddAlgorithm(typeof(CRC211), "CRC211");
            CryptoConfig.AddAlgorithm(typeof(CRC212), "CRC212");
            CryptoConfig.AddAlgorithm(typeof(CRC213), "CRC213");
            CryptoConfig.AddAlgorithm(typeof(CRC214), "CRC214");
            CryptoConfig.AddAlgorithm(typeof(CRC215), "CRC215");
            CryptoConfig.AddAlgorithm(typeof(CRC216), "CRC216");
            CryptoConfig.AddAlgorithm(typeof(CRC217), "CRC217");
            CryptoConfig.AddAlgorithm(typeof(CRC218), "CRC218");
            CryptoConfig.AddAlgorithm(typeof(CRC219), "CRC219");
            CryptoConfig.AddAlgorithm(typeof(CRC220), "CRC220");
            CryptoConfig.AddAlgorithm(typeof(CRC221), "CRC221");
            CryptoConfig.AddAlgorithm(typeof(CRC222), "CRC222");
            CryptoConfig.AddAlgorithm(typeof(CRC223), "CRC223");
            CryptoConfig.AddAlgorithm(typeof(CRC224), "CRC224");
            CryptoConfig.AddAlgorithm(typeof(CRC225), "CRC225");
            CryptoConfig.AddAlgorithm(typeof(CRC226), "CRC226");
            CryptoConfig.AddAlgorithm(typeof(CRC227), "CRC227");
            CryptoConfig.AddAlgorithm(typeof(CRC228), "CRC228");
            CryptoConfig.AddAlgorithm(typeof(CRC229), "CRC229");
            CryptoConfig.AddAlgorithm(typeof(CRC230), "CRC230");
            CryptoConfig.AddAlgorithm(typeof(CRC231), "CRC231");
            CryptoConfig.AddAlgorithm(typeof(CRC232), "CRC232");
            CryptoConfig.AddAlgorithm(typeof(CRC233), "CRC233");
            CryptoConfig.AddAlgorithm(typeof(CRC234), "CRC234");
            CryptoConfig.AddAlgorithm(typeof(CRC235), "CRC235");
            CryptoConfig.AddAlgorithm(typeof(CRC236), "CRC236");
            CryptoConfig.AddAlgorithm(typeof(CRC237), "CRC237");
            CryptoConfig.AddAlgorithm(typeof(CRC238), "CRC238");
            CryptoConfig.AddAlgorithm(typeof(CRC239), "CRC239");
            CryptoConfig.AddAlgorithm(typeof(CRC240), "CRC240");
            CryptoConfig.AddAlgorithm(typeof(CRC241), "CRC241");
            CryptoConfig.AddAlgorithm(typeof(CRC242), "CRC242");
            CryptoConfig.AddAlgorithm(typeof(CRC243), "CRC243");
            CryptoConfig.AddAlgorithm(typeof(CRC244), "CRC244");
            CryptoConfig.AddAlgorithm(typeof(CRC245), "CRC245");
            CryptoConfig.AddAlgorithm(typeof(CRC246), "CRC246");
            CryptoConfig.AddAlgorithm(typeof(CRC247), "CRC247");
            CryptoConfig.AddAlgorithm(typeof(CRC248), "CRC248");
            CryptoConfig.AddAlgorithm(typeof(CRC249), "CRC249");
            CryptoConfig.AddAlgorithm(typeof(CRC250), "CRC250");
            CryptoConfig.AddAlgorithm(typeof(CRC251), "CRC251");
            CryptoConfig.AddAlgorithm(typeof(CRC252), "CRC252");
            CryptoConfig.AddAlgorithm(typeof(CRC253), "CRC253");
            CryptoConfig.AddAlgorithm(typeof(CRC254), "CRC254");
            CryptoConfig.AddAlgorithm(typeof(CRC255), "CRC255");
            CryptoConfig.AddAlgorithm(typeof(CRC256), "CRC256");

            // カタログ記載のアルゴリズム。
            CryptoConfig.AddAlgorithm(typeof(CRC_3_GSM), "CRC-3/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_3_ROHC), "CRC-3/ROHC");
            CryptoConfig.AddAlgorithm(typeof(CRC_4_G_704), "CRC-4/G-704", "CRC-4/ITU");
            CryptoConfig.AddAlgorithm(typeof(CRC_4_INTERLAKEN), "CRC-4/INTERLAKEN");
            CryptoConfig.AddAlgorithm(typeof(CRC_5_EPC_C1G2), "CRC-5/EPC-C1G2", "CRC-5/EPC");
            CryptoConfig.AddAlgorithm(typeof(CRC_5_G_704), "CRC-5/G-704", "CRC-5/ITU");
            CryptoConfig.AddAlgorithm(typeof(CRC_5_USB), "CRC-5/USB");
            CryptoConfig.AddAlgorithm(typeof(CRC_6_CDMA2000_A), "CRC-6/CDMA2000-A");
            CryptoConfig.AddAlgorithm(typeof(CRC_6_CDMA2000_B), "CRC-6/CDMA2000-B");
            CryptoConfig.AddAlgorithm(typeof(CRC_6_DARC), "CRC-6/DARC");
            CryptoConfig.AddAlgorithm(typeof(CRC_6_G_704), "CRC-6/G-704", "CRC-6/ITU");
            CryptoConfig.AddAlgorithm(typeof(CRC_6_GSM), "CRC-6/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_7_MMC), "CRC-7/MMC", "CRC-7");
            CryptoConfig.AddAlgorithm(typeof(CRC_7_ROHC), "CRC-7/ROHC");
            CryptoConfig.AddAlgorithm(typeof(CRC_7_UMTS), "CRC-7/UMTS");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_AUTOSAR), "CRC-8/AUTOSAR");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_BLUETOOTH), "CRC-8/BLUETOOTH");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_CDMA2000), "CRC-8/CDMA2000");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_DARC), "CRC-8/DARC");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_DVB_S2), "CRC-8/DVB-S2");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_GSM_A), "CRC-8/GSM-A");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_GSM_B), "CRC-8/GSM-B");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_I_432_1), "CRC-8/I-432-1", "CRC-8/ITU");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_I_CODE), "CRC-8/I-CODE");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_LTE), "CRC-8/LTE");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_MAXIM_DOW), "CRC-8/MAXIM-DOW", "CRC-8/MAXIM", "DOW-CRC");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_MIFARE_MAD), "CRC-8/MIFARE-MAD");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_NRSC_5), "CRC-8/NRSC-5");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_OPENSAFETY), "CRC-8/OPENSAFETY");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_ROHC), "CRC-8/ROHC");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_SAE_J1850), "CRC-8/SAE-J1850");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_SMBUS), "CRC-8/SMBUS", "CRC-8");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_TECH_3250), "CRC-8/TECH-3250", "CRC-8/AES", "CRC-8/EBU");
            CryptoConfig.AddAlgorithm(typeof(CRC_8_WCDMA), "CRC-8/WCDMA");
            CryptoConfig.AddAlgorithm(typeof(CRC_10_ATM), "CRC-10/ATM", "CRC-10", "CRC-10/I-610");
            CryptoConfig.AddAlgorithm(typeof(CRC_10_CDMA2000), "CRC-10/CDMA2000");
            CryptoConfig.AddAlgorithm(typeof(CRC_10_GSM), "CRC-10/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_11_FLEXRAY), "CRC-11/FLEXRAY", "CRC-11");
            CryptoConfig.AddAlgorithm(typeof(CRC_11_UMTS), "CRC-11/UMTS");
            CryptoConfig.AddAlgorithm(typeof(CRC_12_CDMA2000), "CRC-12/CDMA2000");
            CryptoConfig.AddAlgorithm(typeof(CRC_12_DECT), "CRC-12/DECT", "X-CRC-12");
            CryptoConfig.AddAlgorithm(typeof(CRC_12_GSM), "CRC-12/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_12_UMTS), "CRC-12/UMTS", "CRC-12/3GPP");
            CryptoConfig.AddAlgorithm(typeof(CRC_13_BBC), "CRC-13/BBC");
            CryptoConfig.AddAlgorithm(typeof(CRC_14_DARC), "CRC-14/DARC");
            CryptoConfig.AddAlgorithm(typeof(CRC_14_GSM), "CRC-14/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_15_CAN), "CRC-15/CAN", "CRC-15");
            CryptoConfig.AddAlgorithm(typeof(CRC_15_MPT1327), "CRC-15/MPT1327");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_ARC), "CRC-16/ARC", "ARC", "CRC-16", "CRC-16/LHA", "CRC-IBM");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_CDMA2000), "CRC-16/CDMA2000");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_CMS), "CRC-16/CMS");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_DDS_110), "CRC-16/DDS-110");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_DECT_R), "CRC-16/DECT-R", "R-CRC-16");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_DECT_X), "CRC-16/DECT-X", "X-CRC-16");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_DNP), "CRC-16/DNP");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_EN_13757), "CRC-16/EN-13757");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_GENIBUS), "CRC-16/GENIBUS", "CRC-16/DARC", "CRC-16/EPC", "CRC-16/EPC-C1G2", "CRC-16/I-CODE");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_GSM), "CRC-16/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_IBM_3740), "CRC-16/IBM-3740", "CRC-16/AUTOSAR", "CRC-16/CCITT-FALSE");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_IBM_SDLC), "CRC-16/IBM-SDLC", "CRC-16/ISO-HDLC", "CRC-16/ISO-IEC-14443-3-B", "CRC-16/X-25", "CRC-B", "X-25");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_ISO_IEC_14443_3_A), "CRC-16/ISO-IEC-14443-3-A", "CRC-A");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_KERMIT), "CRC-16/KERMIT", "CRC-16/CCITT", "CRC-16/CCITT-TRUE", "CRC-16/V-41-LSB", "CRC-CCITT", "KERMIT");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_LJ1200), "CRC-16/LJ1200");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_MAXIM_DOW), "CRC-16/MAXIM-DOW", "CRC-16/MAXIM");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_MCRF4XX), "CRC-16/MCRF4XX");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_MODBUS), "CRC-16/MODBUS", "MODBUS");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_NRSC_5), "CRC-16/NRSC-5");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_OPENSAFETY_A), "CRC-16/OPENSAFETY-A");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_OPENSAFETY_B), "CRC-16/OPENSAFETY-B");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_PROFIBUS), "CRC-16/PROFIBUS", "CRC-16/IEC-61158-2");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_RIELLO), "CRC-16/RIELLO");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_SPI_FUJITSU), "CRC-16/SPI-FUJITSU", "CRC-16/AUG-CCITT");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_T10_DIF), "CRC-16/T10-DIF");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_TELEDISK), "CRC-16/TELEDISK");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_TMS37157), "CRC-16/TMS37157");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_UMTS), "CRC-16/UMTS", "CRC-16/BUYPASS", "CRC-16/VERIFONE");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_USB), "CRC-16/USB");
            CryptoConfig.AddAlgorithm(typeof(CRC_16_XMODEM), "CRC-16/XMODEM", "CRC-16/ACORN", "CRC-16/LTE", "CRC-16/V-41-MSB", "XMODEM", "ZMODEM");
            CryptoConfig.AddAlgorithm(typeof(CRC_17_CAN_FD), "CRC-17/CAN-FD");
            CryptoConfig.AddAlgorithm(typeof(CRC_21_CAN_FD), "CRC-21/CAN-FD");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_BLE), "CRC-24/BLE");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_FLEXRAY_A), "CRC-24/FLEXRAY-A");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_FLEXRAY_B), "CRC-24/FLEXRAY-B");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_INTERLAKEN), "CRC-24/INTERLAKEN");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_LTE_A), "CRC-24/LTE-A");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_LTE_B), "CRC-24/LTE-B");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_OPENPGP), "CRC-24/OPENPGP", "CRC-24");
            CryptoConfig.AddAlgorithm(typeof(CRC_24_OS_9), "CRC-24/OS-9");
            CryptoConfig.AddAlgorithm(typeof(CRC_30_CDMA), "CRC-30/CDMA");
            CryptoConfig.AddAlgorithm(typeof(CRC_31_PHILIPS), "CRC-31/PHILIPS");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_AIXM), "CRC-32/AIXM", "CRC-32Q");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_AUTOSAR), "CRC-32/AUTOSAR");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_BASE91_D), "CRC-32/BASE91-D", "CRC-32D");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_BZIP2), "CRC-32/BZIP2", "CRC-32/AAL5", "CRC-32/DECT-B", "B-CRC-32");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_CD_ROM_EDC), "CRC-32/CD-ROM-EDC");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_CKSUM), "CRC-32/CKSUM", "CKSUM", "CRC-32/POSIX");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_ISCSI), "CRC-32/ISCSI", "CRC-32/BASE91-C", "CRC-32/CASTAGNOLI", "CRC-32/INTERLAKEN", "CRC-32C");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_ISO_HDLC), "CRC-32/ISO-HDLC", "CRC-32", "CRC-32/ADCCP", "CRC-32/V-42", "CRC-32/XZ", "PKZIP");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_JAMCRC), "CRC-32/JAMCRC", "JAMCRC");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_MPEG_2), "CRC-32/MPEG-2");
            CryptoConfig.AddAlgorithm(typeof(CRC_32_XFER), "CRC-32/XFER", "XFER");
            CryptoConfig.AddAlgorithm(typeof(CRC_40_GSM), "CRC-40/GSM");
            CryptoConfig.AddAlgorithm(typeof(CRC_64_ECMA_182), "CRC-64/ECMA-182", "CRC-64");
            CryptoConfig.AddAlgorithm(typeof(CRC_64_GO_ISO), "CRC-64/GO-ISO");
            CryptoConfig.AddAlgorithm(typeof(CRC_64_WE), "CRC-64/WE");
            CryptoConfig.AddAlgorithm(typeof(CRC_64_XZ), "CRC-64/XZ", "CRC-64/GO-ECMA");
            CryptoConfig.AddAlgorithm(typeof(CRC_82_DARC), "CRC-82/DARC");

            isRegistered = true;
        }
    }
}
